apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gin
  template:
    metadata:
      labels:
        app: hello-gin
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        readOnlyRootFilesystem: true
        enableServiceLinks: false
      containers:
        - name: hello-gin
          image: harbor.codemowers.eu/hkraav/hanneskraavi/hello-gin:latest
          resources:
            requests:      # Kube scheduleri jaoks, need peaks olema miinimumid
              cpu: 2m      # rate(container_cpu_usage_seconds_total{container="hello-gin"}[1m])
              memory: 15Mi # container_memory_usage_bytes{container="hello-gin"}
            limits:
              cpu: 200m      # CPU throttling
              memory: 100Mi
          env:
            - name: USERNAME
              value: {{ .Values.username }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8080
              name: metrics

